name: CI/CD Pipeline

on:
  push:
    branches: [main, develop]
  pull_request:
    branches: [main, develop]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  quality:
    name: Code Quality
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build --filter=@nexusplay/ui --filter=@nexusplay/core
      - run: npm run check
      - run: npm run lint
      - run: npm run format -- --check
      - run: npm run test

  build-web:
    name: Build Web App
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build:web
        env:
          NEXT_TELEMETRY_DISABLED: 1
      - uses: actions/upload-artifact@v4
        with:
          name: web-build
          path: apps/web/.next
          retention-days: 7

  build-desktop:
    name: Build Desktop App
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    needs: quality
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build:desktop
      - run: npm run build:electron -w @nexusplay/desktop
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: actions/upload-artifact@v4
        with:
          name: desktop-build-${{ matrix.os }}
          path: apps/desktop/build
          retention-days: 7

  build-mobile:
    name: Build Mobile App
    runs-on: ubuntu-latest
    needs: quality
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: android-actions/setup-android@v3
      - run: npm ci
      - run: npm run build:mobile
      - run: npm run build:android -w @nexusplay/mobile
      - uses: actions/upload-artifact@v4
        with:
          name: mobile-build
          path: apps/mobile/android/app/build/outputs
          retention-days: 7

  versioning:
    name: Versioning & Changelog
    runs-on: ubuntu-latest
    needs: [build-web, build-desktop, build-mobile]
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - name: Bump Version & Generate Changelog
        uses: changesets/action@v1
        with:
          version: npm run version
          commit: "chore: release"
          title: "Release v${{ github.run_number }}"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy-web:
    name: Deploy Web App
    runs-on: ubuntu-latest
    needs: versioning
    if: github.ref == 'refs/heads/main'
    environment: production
    env:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          name: web-build
          path: apps/web/.next
      - name: Deploy to Vercel
        run: |
          npm i -g vercel
          vercel --prod --token "$VERCEL_TOKEN" --scope "$VERCEL_ORG_ID" --confirm
        working-directory: apps/web

  deploy-desktop:
    name: Deploy Desktop App
    runs-on: ubuntu-latest
    needs: versioning
    if: github.ref == 'refs/heads/main'
    environment: production
    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v4
        with:
          path: releases
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ github.run_number }}
          name: NexusPlay Desktop v${{ github.run_number }}
          body_path: CHANGELOG.md
          files: releases/**/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  security:
    name: Security Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Run Trivy vulnerability scanner
        uses: aquasecurity/trivy-action@0.22.0
        with:
          scan-type: 'fs'
          scan-ref: '.'
          format: 'sarif'
          output: 'trivy-results.sarif'
      - uses: github/codeql-action/upload-sarif@v3
        with:
          sarif_file: 'trivy-results.sarif'

  lighthouse:
    name: Lighthouse Audit
    runs-on: ubuntu-latest
    needs: build-web
    if: github.event_name == 'pull_request'
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
      - run: npm ci
      - run: npm run build:web
      - run: npm run start -w @nexusplay/web &
        env:
          PORT: 3000
      - run: npx wait-on http://localhost:3000
      - uses: treosh/lighthouse-ci-action@v12
        with:
          urls: |
            http://localhost:3000
            http://localhost:3000/optimizer
            http://localhost:3000/gear
          configPath: ./.github/lighthouse/config.json
          uploadArtifacts: true
          temporaryPublicStorage: true
